'use client';
import { useState, useEffect } from 'react';

export default function LaunchApp() {
  const [input, setInput] = useState('');
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [mounted, setMounted] = useState(false);

  useEffect(() => { setMounted(true); }, []);

  const runMeeting = async () => {
    if (!input) return;
    setLoading(true);
    try {
      const res = await fetch('/api/chat', { method: 'POST', body: JSON.stringify({ prompt: input }) });
      const result = await res.json();
      setData(result);
    } catch (e) { console.error(e); }
    setLoading(false);
  };

  if (!mounted) return <div className="min-h-screen bg-black" />;

  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100 font-sans p-4 md:p-10">
      <div className="max-w-5xl mx-auto">
        {/* Header - Hidden on Print */}
        <header className="mb-10 text-center print:hidden">
          <h1 className="text-4xl font-black tracking-tighter text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-emerald-400">
            LAUNCH AI: WAR ROOM
          </h1>
          <p className="text-zinc-500 mt-2 text-sm uppercase tracking-widest">Strategic Intelligence Report</p>
        </header>

        {/* Input Area - Hidden on Print */}
        <div className="space-y-6 print:hidden">
          <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-2 shadow-2xl">
            <textarea 
              className="w-full bg-transparent p-4 h-40 outline-none resize-none text-lg"
              placeholder="Describe your business concept..."
              value={input}
              onChange={(e) => setInput(e.target.value)}
            />
            <button 
              onClick={runMeeting}
              disabled={loading}
              className="w-full py-4 bg-blue-600 rounded-xl font-bold uppercase hover:bg-blue-500 transition-all disabled:opacity-50"
            >
              {loading ? "Analyzing..." : "Generate Business Blueprint"}
            </button>
          </div>
        </div>

        {/* The Result Area - This is what gets printed */}
        {data && (
          <div className="mt-10 animate-in fade-in slide-in-from-bottom-4 duration-700">
            
            {/* Action Buttons - Hidden on Print */}
            <div className="flex justify-end mb-4 print:hidden">
              <button 
                onClick={() => window.print()}
                className="px-6 py-2 bg-zinc-800 hover:bg-zinc-700 border border-zinc-700 rounded-lg text-sm font-medium flex items-center gap-2"
              >
                💾 Save as PDF / Print
              </button>
            </div>

            <div className="bg-white text-black p-8 md:p-12 rounded-2xl shadow-2xl print:shadow-none print:p-0">
              <div className="border-b-2 border-blue-600 pb-4 mb-8">
                <h2 className="text-3xl font-black uppercase tracking-tight">Executive Blueprint</h2>
                <p className="text-zinc-500 text-sm italic">Generated by LaunchAI Board of Directors • {new Date().toLocaleDateString()}</p>
              </div>

              <div className="mb-10">
                <h3 className="text-blue-600 font-bold uppercase text-xs mb-4 tracking-widest text-center md:text-left">Architect's Final Recommendation</h3>
                <div className="text-lg leading-relaxed whitespace-pre-wrap italic border-l-4 border-blue-100 pl-6">
                  {data.architect}
                </div>
              </div>

              <div className="grid grid-cols-1 gap-8 pt-8 border-t border-zinc-100">
                {data.board.map((member: any) => (
                  <div key={member.name} className="break-inside-avoid">
                    <h4 className="text-blue-600 font-bold uppercase text-[10px] mb-2">{member.name} Analysis</h4>
                    <p className="text-zinc-700 text-sm leading-relaxed">{member.text}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
